theme = 'everforest_dark'

[editor]
line-number = 'relative'
mouse = true
cursorline = true
rulers = [100]

[editor.file-picker]
hidden = false

[keys.normal]
";" = "command_mode"
"$" = "goto_line_end"
"0" = "goto_line_start"
"'" = "collapse_selection"
space= { x = ":buffer-close" }

[keys.select]
";" = "command_mode"
"$" = "goto_line_end"
"0" = "goto_line_start"
"'" = "collapse_selection"
