return {
  { "lazydev.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "mini.ai", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "catppuccin/nvim", enabled = false },
  { "MagicDuck/grug-far.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "mfussenegger/nvim-lint", enabled = false },
  { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
  { "windwp/nvim-ts-autotag", enabled = false },
  { "blink.cmp", enabled = false },
  { "flash.nvim", enabled = false },
  { "friendly-snippets", enabled = false },
  { "gitsigns.nvim", enabled = false },
  { "mason-lspconfig.nvim", enabled = false },
  { "mason.nvim", enabled = false },
  { "nvim-lspconfig", enabled = false },
  { "nvim-treesitter", enabled = false },
}
